export const testTopics = [
  { name: 'Cardiology' },
  { name: 'Neurology' },
  { name: 'Oncology' },
  { name: 'Pediatrics' },
  { name: 'Orthopedics' },
  { name: 'Dermatology' },
  { name: 'Gastroenterology' },
  { name: 'Psychiatry' },
  { name: 'Radiology' },
  { name: 'Endocrinology' },
]

export const testTags = [
  { name: 'Heart Disease', topicId: 1 },
  { name: 'Hypertension', topicId: 1 },
  { name: 'Stroke', topicId: 2 },
  { name: 'Epilepsy', topicId: 2 },
  { name: 'Breast Cancer', topicId: 3 },
  { name: 'Chemotherapy', topicId: 3 },
  { name: 'Childhood Vaccination', topicId: 4 },
  { name: 'Pediatric Asthma', topicId: 4 },
  { name: 'Joint Replacement', topicId: 5 },
  { name: 'Fracture Treatment', topicId: 5 },
  { name: 'Acne', topicId: 6 },
  { name: 'Psoriasis', topicId: 6 },
  { name: 'Irritable Bowel Syndrome', topicId: 7 },
  { name: 'Liver Disease', topicId: 7 },
  { name: 'Depression', topicId: 8 },
  { name: 'Anxiety Disorders', topicId: 8 },
  { name: 'X-ray Imaging', topicId: 9 },
  { name: 'MRI Scans', topicId: 9 },
  { name: 'Diabetes Management', topicId: 10 },
  { name: 'Thyroid Disorders', topicId: 10 },
]
export const testQuestions = [
  {
    name: 'Test Case 1',
    case: 'The discovery of a new species of bird in the Amazon rainforest',
    question: 'What is the primary diet of the newly discovered bird species?',
    type: 'AKT',
    multipleChoiceOptions: [
      'Fruits and seeds',
      'Small insects and larvae',
      'Fish and small amphibians',
      'Nectar from flowers',
      'Leaves and twigs',
    ],
    topics: [{ id: 4 }, { id: 7 }],
    tags: [{ id: 13 }, { id: 2 }],
  },
  {
    name: 'Test Case 2',
    case: 'The introduction of electric buses in a major city',
    question: 'What is one of the main advantages of using electric buses?',
    type: 'AKT',
    multipleChoiceOptions: [
      'Reduced air pollution',
      'Lower fuel costs',
      'Quieter operation',
      'Increased passenger capacity',
    ],
    topics: [{ id: 2 }, { id: 5 }],
    tags: [{ id: 16 }, { id: 7 }, { id: 18 }],
  },
  {
    name: 'Test Case 3',
    case: 'The effects of a new diet plan on weight loss',
    question: 'Which food group is most emphasized in the new diet plan?',
    type: 'AKT',
    multipleChoiceOptions: [
      'Vegetables',
      'Proteins',
      'Carbohydrates',
      'Fats',
      'Sugars',
    ],
    topics: [{ id: 6 }],
    tags: [{ id: 10 }, { id: 15 }],
  },
  {
    name: 'Test Case 4',
    case: 'A study on the impact of sleep on cognitive function',
    type: 'AKT',
    question:
      'How many hours of sleep were found to be optimal for cognitive performance?',
    multipleChoiceOptions: [
      '6 hours',
      '7 hours',
      '8 hours',
      '9 hours',
      '10 hours',
    ],
    topics: [{ id: 1 }, { id: 8 }, { id: 3 }],
    tags: [{ id: 11 }, { id: 20 }],
  },
  {
    name: 'Test Case 5',
    case: 'A report on the economic benefits of renewable energy',
    type: 'AKT',
    question:
      'Which renewable energy source was found to be the most cost-effective?',
    multipleChoiceOptions: [
      'Solar power',
      'Wind power',
      'Hydroelectric power',
      'Geothermal power',
      'Biomass energy',
    ],
    topics: [{ id: 9 }, { id: 10 }],
    tags: [{ id: 8 }],
  },
  {
    name: 'Test Case 6',
    case: 'The impact of social media on mental health in teenagers',
    type: 'AKT',
    question:
      'What is a common negative effect of excessive social media use in teenagers?',
    multipleChoiceOptions: [
      'Increased anxiety',
      'Better communication skills',
      'Improved academic performance',
      'More social connections',
    ],
    topics: [{ id: 3 }, { id: 7 }],
    tags: [{ id: 5 }, { id: 14 }, { id: 19 }],
  },
  {
    name: 'Test Case 7',
    case: 'A new law requiring the use of helmets for cyclists',
    type: 'AKT',
    question: 'What is the primary reason for implementing the helmet law?',
    multipleChoiceOptions: [
      'To reduce head injuries',
      'To increase cycling popularity',
      'To improve traffic flow',
      'To promote physical fitness',
    ],
    topics: [{ id: 1 }],
    tags: [{ id: 6 }, { id: 12 }],
  },
  {
    name: 'Test Case 8',
    case: 'A breakthrough in cancer treatment using gene therapy',
    type: 'AKT',
    question:
      'What type of cancer was most effectively treated with the new gene therapy?',
    multipleChoiceOptions: [
      'Breast cancer',
      'Lung cancer',
      'Leukemia',
      'Prostate cancer',
      'Skin cancer',
    ],
    topics: [{ id: 2 }, { id: 5 }, { id: 9 }],
    tags: [{ id: 1 }, { id: 4 }],
  },
  {
    name: 'Test Case 9',
    case: 'The effects of climate change on coastal cities',
    type: 'AKT',
    question:
      'What is a major risk faced by coastal cities due to climate change?',
    multipleChoiceOptions: [
      'Rising sea levels',
      'Increased tourism',
      'More job opportunities',
      'Decreased air quality',
    ],
    topics: [{ id: 4 }, { id: 8 }],
    tags: [{ id: 9 }, { id: 17 }, { id: 3 }],
  },
  {
    name: 'Test Case 10',
    case: 'The introduction of AI in customer service',
    type: 'AKT',
    question: 'What is a key benefit of using AI in customer service?',
    multipleChoiceOptions: [
      '24/7 availability',
      'Higher costs',
      'Slower response times',
      'Limited language support',
    ],
    topics: [{ id: 6 }],
    tags: [{ id: 2 }, { id: 11 }],
  },
]
